services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Service\PhoenixApiClientInterface:
        alias: App\Service\PhoenixApiClient

    App\Service\PhoenixApiClient:
        arguments:
            $phoenixBaseUrl: '%env(PHOENIX_BASE_URL)%'

when@test:
    services:
        App\Tests\TestDoubles\PhoenixApiClientStub:
            public: true

        App\Service\PhoenixApiClientInterface:
            alias: App\Tests\TestDoubles\PhoenixApiClientStub
