security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\HomeRedirectEntryPoint
            custom_authenticators:
                - App\Security\TokenUrlAuthenticator
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/photo, roles: ROLE_USER }
