_security_logout:
    resource: security.route_loader.logout
    type: service

auth_login:
    path: /auth/{username}/{token}
    methods: [GET]
    requirements:
        username: '[a-zA-Z0-9_]+'
        token: '[a-f0-9]+'
